apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-componentpart-cm-sql
data:
  logstash.conf: |-
    input {
       jdbc {
            type => "solumina_component_part"
            jdbc_driver_library => "/opt/logstash/driver/sqljdbc4.jar"
            jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"
            jdbc_connection_string => "jdbc:sqlserver://--sqlip--;applicationName=SoluminaFND;instanceName=--instance_name--;databaseName=Solumina;schemaName=SFMFG;sendStringParametersAsUnicode=false"
            jdbc_user => "MT_CONPOOL_USER"
            jdbc_password => "MT_CONPOOL_USER"
            jdbc_fetch_size => 1000
            schedule => "*/5 * * * *"
            statement => "select distinct concat('componentpart',c.rowid) as rid_obj, a.order_id, a.order_no, b.oper_key, b.oper_no, c.part_no, a.security_group from sfwid_order_desc a, sfwid_oper_desc b, sfwid_oper_items c where a.order_id = b.order_id and b.step_key = -1 and c.order_id = b.order_id and c.oper_key = b.oper_key and DATEADD(second, datediff(second, getdate(), getutcdate()), c.time_stamp) >= :sql_last_value"
            clean_run => false
            record_last_run => true
            sql_log_level => debug
            last_run_metadata_path => "/opt/logstash/lastrun/.logstash_jdbc_last_run_component_part"
            connection_retry_attempts_wait_time => 30
            connection_retry_attempts => 99999999
        }
     }
    filter {
      if[type] == "solumina_component_part" {
        mutate {
          replace => { "type" => "component_part" }
          }
      }
    }
    output {
      elasticsearch {
        hosts => "https://--es--:443"
        index => "<solumina-component_partsearch-{now/d{YYYY.MM.dd}}>"
        document_id => "%{rid_obj}"
      }
    }

  logstash.yml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.enabled: false
