apiVersion: v1
data:
  logback.xml: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<configuration>\n\t<property
    name=\"CONSOLE_LOG_PATTERN\" value=\"%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- }
    [%t] --- %-40.40logger{39} : %m%n%wex\"/>\n\n\t<conversionRule conversionWord=\"wex\"
    converterClass=\"org.springframework.boot.logging.logback.WhitespaceThrowableProxyConverter\"
    />\n\n\t<appender name=\"CONSOLE\" class=\"ch.qos.logback.core.ConsoleAppender\">\n\t\t<encoder>\n\t\t\t<pattern>${CONSOLE_LOG_PATTERN}</pattern>\n\t\t</encoder>\n\t</appender>\n\n\t<appender
    name=\"FILE\" class=\"ch.qos.logback.core.rolling.RollingFileAppender\">\n\t\t<file>logs/operations-elasticsearch.log</file>\n\t\t<rollingPolicy
    class=\"ch.qos.logback.core.rolling.FixedWindowRollingPolicy\">\n\t\t\t<fileNamePattern>logs/operations-elasticsearch.%i.log.zip</fileNamePattern>\n\t\t\t<minIndex>1</minIndex>\n\t\t\t<maxIndex>10</maxIndex>\n\t\t</rollingPolicy>\n\t\t<triggeringPolicy
    class=\"ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy\">\n\t\t\t<maxFileSize>5MB</maxFileSize>\n\t\t</triggeringPolicy>\n\t\t<encoder>\n\t\t\t<pattern>${CONSOLE_LOG_PATTERN}</pattern>\n\t\t</encoder>\n\t</appender>\n\n\t<root
    level=\"ERROR\">\n\t\t<appender-ref ref=\"CONSOLE\" />\n\t</root>\n\t\n\t<logger
    name=\"org.springframework\" level=\"WARN\"/>\n\t<logger name=\"com.ibaset.solumina\"
    level=\"ERROR\"/>\n\t\n</configuration>"
kind: ConfigMap
metadata:
  creationTimestamp: 2019-06-03T21:20:01Z
  name: search-cm-logback
  namespace: default
  resourceVersion: "404199"
  selfLink: /api/v1/namespaces/default/configmaps/search-logback
  uid: 591beacb-8645-11e9-9ba1-0af663ddcdfa

