USE Solumina;
GRANT ALTER ON OBJECT::SFMFG.SFCORE_LICENSE_KEY
    TO MT_CONPOOL_USER;
GO
 
USE Solumina;
GRANT ALTER ON OBJECT::SFMFG.SFCORE_LICENSE_PREFIX
    TO MT_CONPOOL_USER;
GO
 
USE Solumina;
GRANT ALTER ON OBJECT::SFMFG.SFCORE_GET_LICENSING_MODE
    TO MT_CONPOOL_USER;
GO
 
USE Solumina;
GRANT ALTER ON OBJECT::SFMFG.SFCORE_LTA_ENABLED
    TO MT_CONPOOL_USER;
GO
 
USE Solumina;
GRANT ALTER ON OBJECT::SFMFG.SFCORE_XML_ENABLED
    TO MT_CONPOOL_USER;
GO
