AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an empty SQL Server RDS database as an example for automated deployments.
Parameters:
  SqlServerInstanceName:
    Description: RDS SQL Server Instance Name
    Type: String
  #  Default: SqlRdsDB
  #  MinLength: '1'
  #  MaxLength: '63'
  #  AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
  DatabaseUsername:
  #  AllowedPattern: "[a-zA-Z0-9]+"
  #  ConstraintDescription: must contain only alphanumeric characters.
    Description: The database admin account user name.
  #  MaxLength: '16'
  #  MinLength: '1'
    Type: String
  DatabasePassword:
  #  AllowedPattern: "^(?=.*[0-9])(?=.*[a-zA-Z])([a-zA-Z0-9]+)"
  #  ConstraintDescription: Must contain only alphanumeric characters with at least one capital letter and one number.
    Description: The database admin account password.
  #  MaxLength: '41'
  #  MinLength: '8'
  #  NoEcho: 'true'
    Type: String
  VpcId:
    Description: ID of the VPC (e.g., vpc-0343606e).
    Type: AWS::EC2::VPC::Id
  AllocatedStorage:
  #  ConstraintDescription: "Must be a valid Number from 100 GiB to 5120 GiB"
  #  Default: "100"
    Description: "Enter the number of Gigabytes for RDS, between 100 GiB and 5120 GiB (5 TiB)."
    Type: Number
  #  MinValue: '100'
  #  MaxValue: '5120'
  SqlServerVersion:
    #Default: "SQLServer2016"
    Description: "Enter the SQL Server version. SQLServer2012 and 2016 are supported."
    Type: String
    #AllowedValues:
    #  - "SQLServer2016"
    #  - "SQLServer2012"
  PrivateSubnet1:
    Description: Private subnet ID
    Type: String
  PrivateSubnet2:
    Description: Private subnet ID
    Type: String
  PrivateSubnet3:
    Description: Private subnet ID
    Type: String
  #PrivateSubnets:
  #  Description: List of private subnet ids to deploy SQL Server
    #Type: List<AWS::EC2::Subnet::Id>
  #  Type: String
    #Type: "AWS::EC2::Subnet::Id"
  DBInstanceClass: 
    Type: String
    #AllowedValues: 
    #  - db.r4.large
    #  - db.r4.xlarge
    #  - db.r4.2xlarge
    #  - db.r4.4xlarge
    #  - db.r4.8xlarge
    #  - db.r4.16xlarge
    #  - db.r5.large
    #  - db.r5.xlarge
    #  - db.r5.2xlarge
    #  - db.r5.4xlarge
    #  - db.r5.12xlarge
    #  - db.r5.24xlarge
    #  - db.m4.large
    #  - db.m4.xlarge
    #  - db.m4.2xlarge
    #  - db.m4.4xlarge
    #  - db.m4.10xlarge
    #  - db.m4.16xlarge
    #  - db.m5.large
    #  - db.m5.xlarge
    #  - db.m5.2xlarge
    #  - db.m5.4xlarge
    #  - db.m5.12xlarge
    #  - db.m5.24xlarge
    #ConstraintDescription: "Must select a valid database instance type."
    #Default: db.m4.large
    #Description: "The name of the compute and memory capacity class of the database instance."
Mappings: 
  SqlServerVersionCode: 
    "SQLServer2016": 
      Code: "13.00.5216.0.v1"
    "SQLServer2012": 
      Code: "11.00.7462.6.v1"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: SQL Instance name, master username, password, and other settings
      Parameters:
        - SqlServerInstanceName
        - DatabaseUsername
        - DatabasePassword
        - VpcId
        - AllocatedStorage
        - SqlServerVersion
        - DBInstanceClass
      ParameterLabels:
        SqlServerInstanceName:
            default: Instance name
        DatabaseUsername:
            default: Master user name
        DatabasePassword:
            default: Password
Resources:
  SQLServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SQL Server Security Group
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '1433'
        ToPort: '1433'
        CidrIp: 0.0.0.0/0
      VpcId:
        Ref: VpcId
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Group of private subnets for SQL Server
      SubnetIds: 
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
        - !Ref PrivateSubnet3
  SQLDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      VPCSecurityGroups:
      - Fn::GetAtt:
        - SQLServerSecurityGroup
        - GroupId
      DBSubnetGroupName:
        Ref: DBSubnetGroup
      DBInstanceIdentifier:
        Ref: SqlServerInstanceName
      LicenseModel: license-included
      Engine: sqlserver-se
      EngineVersion: 
        !FindInMap
        - SqlServerVersionCode
        - !Ref SqlServerVersion
        - Code
      MultiAZ: false
      DBInstanceClass:
        !Ref DBInstanceClass
      AllocatedStorage:
        !Ref AllocatedStorage
      MasterUsername:
        Ref: DatabaseUsername
      MasterUserPassword:
        Ref: DatabasePassword
      PubliclyAccessible: 'false'
      Tags:
        -
          Key: "Name"
          Value: "sqlmaster"
        -
          Key: "project"
          Value: "development unittest"
      BackupRetentionPeriod: '1'
    DependsOn: SQLServerSecurityGroup
Outputs:
   SQLDatabaseEndpoint:
     Description: Database endpoint
     Value: !Sub "${SQLDatabase.Endpoint.Address}:${SQLDatabase.Endpoint.Port}"
   SQLDatabaseEndpointURL:
     Description: Database endpoint URL
     Value: !Sub "${SQLDatabase.Endpoint.Address}"