apiVersion: v1
data:
  mediaConfig: |
    PORT=5031
    ZIPKIN_SERVER_URL=https://--DNS_NAME--/diagnostics
    TOKEN_SECRET=solumina+$ibaset
    AUTH_API_ENDPOINT=/authorizations/
    SERVICE_NAME=media
    MIDDLE_TIER=solumina-G8
    ENABLE_CUSTOM_THEME=false
    APP_HOST_NAME=https://--DNS_NAME--
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: media-cm
