apiVersion: v1
data:
  .env: |
    PORT=8050
    DB_URI=mongodb://solumina_config:solumina_config@--mongoprimaryip--:27017,--mongosecondaryip0--:27017,--mongosecondaryip1--:27017/solumina_config?replicaSet=s0
    replicaSet=s0
    DB_POOLSIZE=20
    DB_RECONNECT_INTERVAL=500
    DB_RECONNECT_TRIES=30
    DB_MIN_SIZE=10
    DB_SOCKET_TIMEOUT_MS=360000
    DB_LOGGER_LEVEL=error
    DB_KEEP_ALIVE=10000
    DB_BUFFER_MAX_ENTRIES=10
    DB_AUTO_INDEX=false
    TOKEN_SECRET=solumina+$ibaset
kind: ConfigMap
metadata:
  name: configurator-api-cm
  namespace: default
