apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  labels:
    app: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: "279559645400.dkr.ecr.us-west-1.amazonaws.com/solui/login-view:G8R2SP4"
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: login-config
          mountPath: /opt/ibaset/solumina-web-login/config/


      volumes:
       - name: login-config
         configMap:
            defaultMode: 420
            items:
            - key: loginconfig
              path: .env
            name: login-cm
