apiVersion: v1
kind: Service
metadata:

  labels:
    app: elk-cron
  name: elk-cron
spec:
  selector:
    app: elk-cron
  ports:
  - name: elk-cron
    protocol: TCP
    port: 9091
    targetPort: 9091

#  externalIPs:
#   - 10.3.5.168
status:
  loadBalancer: {}