apiVersion: v1
data:
  application-sqlserver.yml: |-
    # Sql-Server configuration
    app:
      db-name: microsoftSQLServer

    datasource:
      driverClass: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbcUrl: CONN_STRING
      username: MT_CONPOOL_USER
      password: MT_CONPOOL_USER
      maximumPoolSize: 200
      minimumIdle: 25
      connectionTestQuery: select getdate()
      autoCommit: false
      connectionTimeout: 120000
      idleTimeout: 30000
      leakDetectionThreshold: 180000
      validationTimeout: 10000
      maxLifetime: 1800000
      implicitCachingEnabled: true
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: elk-cron-application-sqlserver-cm
