apiVersion: v1
data:
  application.yml: |-
    server:
      port: 9091
      servlet:
        context-path: /solumina-elk/api
    spring:
      profiles:
        include:
         - tomcat # must have profile
         - redis # must have profile
         - ACTIVATED_PROFILE_FOR_DATABASE # Possible values - oracle, sqlserver
      devtools:
        restart:
          exclude: logs/**
      main:
         allow-bean-definition-overriding: true
      cloud:
        refresh:
          enabled: false
      autoconfigure:
        exclude:
           - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
           - org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration
           - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    elastic:
       hostnames: elasticsearch-coordinator
       port: 9200
       maxthreads: 10
       retrytimeout: 10000

    security:
      oauth2:
        resource:
          jwt:
            key-value: solumina+$ibaset
    defaultSchema: SFMFG
    solumina.elk.delete.cronJobTime: 0 */10 * ? * *
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: elk-cron-application-cm
