apiVersion: v1
data:
  application-oracle.yml: |
    # Oracle DB configuration
    app:
      db-name: oracle
      datasource:
        jdbc-url: jdbc:oracle:thin:@dexui.c4jsc5ks7f1j.us-west-1.rds.amazonaws.com:1521:DEXUI
        username: MT_CONPOOL_USER
        password: mt_conpool_user
        driver-class-name: oracle.jdbc.driver.OracleDriver
        default-auto-commit: false
        max-idle: 25
        min-idle: 25
        max-wait: 2
        validation-query: select sysdate from dual
        max-active: 50
kind: ConfigMap
metadata:
  creationTimestamp: 2019-06-11T17:12:21Z
  name: userinfo-cm-oracle
  namespace: default
  resourceVersion: "1431084"
  selfLink: /api/v1/namespaces/default/configmaps/userinfo-cm-oracle
  uid: 13318e0b-8c6c-11e9-b6be-06e36b0b2240
