apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
      - name: redis-master
        ports:
         - containerPort: 6379
        image: "279559645400.dkr.ecr.us-west-1.amazonaws.com/redis/server:v1.0.0"
      restartPolicy: Always
status: {}

