
apiVersion: v1
data:
  application-sqlserver.yml: |
    # Sql-Server configuration
    app:
      db-name: microsoftSQLServer
    datasource:
      driverClass: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbcUrl: CONN_STRING
      username: MT_CONPOOL_USER
      password: MT_CONPOOL_USER
      maximumPoolSize: 25
      minimumIdle: 10
      connectionTestQuery: select getdate()
      autoCommit: false
      connectionTimeout: 120000
      idleTimeout: 30000
      leakDetectionThreshold: 180000
      validationTimeout: 10000
      maxLifetime: 1800000
      implicitCachingEnabled: true
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
    #warehouseDatasource:
    #  driverClass: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #  jdbcUrl: CONN_STRING
    #  username: MT_CONPOOL_USER
    #  password: MT_CONPOOL_USER
    #  maximumPoolSize: 25
    #  minimumIdle: 10
    #  connectionTestQuery: select getdate()
    #  autoCommit: false
    #  connectionTimeout: 120000
    #  idleTimeout: 30000
    #  leakDetectionThreshold: 180000
    #  validationTimeout: 10000
    #  maxLifetime: 1800000
    #  implicitCachingEnabled: true
    #  cachePrepStmts: true
    #  prepStmtCacheSize: 250
    #  prepStmtCacheSqlLimit: 2048
    #  useServerPrepStmts: true
    spring:
      quartz:
        properties:
          org:
            quartz:
              jobStore:
                driverDelegateClass: org.quartz.impl.jdbcjobstore.MSSQLDelegate
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cron-applicationsqlserver-cm
