apiVersion: v1
data:
  application.yml: |
    server:
      servlet:
        context-path: /solumina-cron-microservice/api
      port: 8092
    spring:
      profiles:
        include:
         - tomcat # must have profile
         - redis # must have profile
         - ACTIVATED_PROFILE_FOR_DATABASE # Possible values - oracle, sqlserver
      devtools:
        restart:
          exclude: logs/**
      servlet:
        multipart:
          max-file-size: 100MB
          max-request-size: 100MB
      main:
         allow-bean-definition-overriding: true
      cloud:
        refresh:
          enabled: false
      autoconfigure:
        exclude:
           - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
           - org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration
           - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      quartz:
        job-store-type: jdbc
        properties:
          org:
            quartz:
              jobStore:
                isClustered: false
                class: org.quartz.impl.jdbcjobstore.JobStoreCMT
                tablePrefix: SFQRTZ_
              scheduler:
                instanceId: AUTO
              threadPool:
                threadCount: 10
        jdbc:
          initialize-schema: never
    security:
      oauth2:
        resource:
          jwt:
            key-value: solumina+$ibaset
    defaultSchema: SFMFG
    quartzCronGroup: SFQRTZ_CRON_GROUP
    zipkin:
      server:
        url: http://zipkin:9411

    solumina:
      serviceName: cron
    management:
      endpoints:
        enabled-by-default: false
      metrics:
        use-global-registry: false
        export:
          elastic:
            enabled: false
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cron-application-cm
