apiVersion: v1
kind: Service
metadata:

  labels:
    app: cron
  name: cron
spec:
  selector:
    app: cron
  ports:
  - name: cron
    protocol: TCP
    port: 8092
    targetPort: 8092

#  externalIPs:
#   - 10.3.5.168
status:
  loadBalancer: {}
