apiVersion: v1
data:
  jgroupconfig.xml: |
    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="urn:org:jgroups"
            xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups.xsd">
        <TCP bind_port="7800"
             recv_buf_size="${tcp.recv_buf_size:130k}"
             send_buf_size="${tcp.send_buf_size:130k}"
             max_bundle_size="64K"
             sock_conn_timeout="300"

             thread_pool.min_threads="0"
             thread_pool.max_threads="20"
             thread_pool.keep_alive_time="30000"/>

        <JDBC_PING clear_table_on_view_change="true"
           datasource_jndi_name="java:comp/env/jdbc/jgroupcluster"
           initialize_sql=""
           insert_single_sql="INSERT INTO SFFND_JGROUPSPING (own_addr, bind_addr, created, cluster_name, ping_data) values (?,'${jgroups.bind_addr:127.0.0.1}',current_timestamp, ?, ?)"
           delete_single_sql="DELETE FROM SFFND_JGROUPSPING WHERE own_addr=? AND cluster_name=?"
           select_all_pingdata_sql="SELECT ping_data FROM SFFND_JGROUPSPING WHERE cluster_name=?"
           contains_sql="SELECT count(own_addr) as RECORDCOUNT from SFFND_JGROUPSPING WHERE cluster_name=? AND own_addr=?"
           clear_sql="DELETE FROM SFFND_JGROUPSPING"
        />

        <MERGE3  min_interval="10000"
                 max_interval="30000"/>
        <FD_SOCK/>
        <FD timeout="3000" max_tries="3" />
        <VERIFY_SUSPECT timeout="1500"  />
        <BARRIER />
        <pbcast.NAKACK2 use_mcast_xmit="false"
                       discard_delivered_msgs="true"/>
        <!-- <UNICAST3 /> -->
        <pbcast.STABLE desired_avg_gossip="50000"
                       max_bytes="4M"/>
        <pbcast.GMS print_local_addr="true" join_timeout="2000"/>
        <MFC max_credits="2M"
             min_threshold="0.4"/>
        <FRAG2 frag_size="60K"  />
        <!--RSVP resend_interval="2000" timeout="10000"/-->
        <pbcast.STATE_TRANSFER/>
    </config>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: iba-jgroupconfig-cm
