apiVersion: v1
data:
  redis.properties: |
    redis.tokenrevocation.enabled=true
    redis.cluster.sentinel.nodes=redis://redis-sentinel-1.default.svc.cluster.local:26379,redis://redis-sentinel-2.default.svc.cluster.local:26379
    redis.cluster.sentinel.master=mymaster
    redis.cluster.pool.maxconnection=128

    ##spring.redis.cluster.nodes[0]=--DNS_NAME--:6379
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: iba-redis-cm
