apiVersion: v1
data:
  solumina-G8.xml: |
    <Context useHttpOnly="true" path="/solumina-G8"
        docBase="${catalina.home}/solumina/solumina-G8R2i020.war">
            <Resource
                    auth="Container"
                    name="jdbc/soluminaPrivateDS"
                    type="javax.sql.DataSource"
                    username="MT_CONPOOL_USER"
                    password="MT_CONPOOL_USER"
                    driverClassName="--DB_DRIVER--"
                    defaultAutoCommit="false"
                    maxIdle="25"
                    maxWaitMillis="2"
                    minIdle="25"
                    validationQuery="VALIDATION_QUERY"
                    url="CONN_STRING"
                    maxTotal="50"/>
    <!--Uncomment for JGroups JDBC Ping for SQL Server -->
            <Resource
                    auth="Container"
                    name="jdbc/jgroupcluster"
                    type="javax.sql.DataSource"
                    username="MT_CONPOOL_USER"
                    password="MT_CONPOOL_USER"
                    driverClassName="--DB_DRIVER--"
                    defaultAutoCommit="true"
                    maxIdle="25"
                    maxWaitMillis="2"
                    minIdle="25"
                    validationQuery="VALIDATION_QUERY"
                    url="CONN_STRING"
                    maxTotal="50"/>
        <Resource name="jms/ConnectionFactory"
            auth="Container"
            type="org.apache.activemq.ActiveMQConnectionFactory"
            factory="org.apache.activemq.jndi.JNDIReferenceFactory"
            brokerURL="ACTIVEMQ_ADDRESS" />
        <Resources className="org.apache.catalina.webresources.StandardRoot">
            <PreResources
                className="org.apache.catalina.webresources.DirResourceSet"
                base="/opt/config/driver"
                webAppMount="/WEB-INF/lib" />
            <PreResources
                className="org.apache.catalina.webresources.DirResourceSet"
                base="/opt/config/props"
                webAppMount="/WEB-INF/classes" />
        </Resources>
    </Context>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: iba-solumina-g8-cm
