apiVersion: v1
data:
  soluminaConfig.properties: |-
    # Spring prfiles to be activated
    spring.profiles.active=tomcat,activeMQ,redis,ACTIVATED_PROFILE_FOR_DATABASE
    #############################
    #############################
    # External Microservices Configuration
    #############################
    docconverter.scheme=http
    docconverter.host=converter
    docconverter.port=8090
    zipkin.server.url=http://--DNS_NAME--
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: iba-soluminaconfig-cm
