apiVersion: v1
data:
  ibaIntegrationExtensionContext.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <!--

        Proprietary and Confidential
        Copyright 1995-2015 iBASEt, Inc.
        Unpublished-rights reserved under the Copyright Laws of the United States
        US Government Procurements:
        Commercial Software licensed with Restricted Rights.
        Use, reproduction, or disclosure is subject to restrictions set forth in
        license agreement and purchase contract.
        iBASEt, Inc. 27442 Portola Parkway, Suite 300, Foothill Ranch, CA 92610

        Solumina software may be subject to United States Dept of Commerce Export Controls.
        Contact iBASEt for specific Expert Control Classification information.

    -->
    <beans xmlns="http://www.springframework.org/schema/beans"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:jms="http://www.springframework.org/schema/jms"
            xmlns:aop="http://www.springframework.org/schema/aop"
            xmlns:tx="http://www.springframework.org/schema/tx"
            xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.3.xsd
        http://www.springframework.org/schema/jms http://www.springframework.org/schema/jms/spring-jms-2.1.xsd
        http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-2.0.xsd
        http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-4.3.xsd"
            default-lazy-init="false"
            default-autowire="no">

            <!-- ALL BEAN DEFINITIONS THAT DEPENDS ON BEANS IN integrationContext.xml SHOULD GO IN integrationExtensionContext.xml -->

    <bean id="listenerRegistry"
            class="com.ibaset.solumina.integration.inbound.IntegrationInboundServiceRegistry" destroy-method="cleanUp">
            <property name="connectionFactory" ref="connectionFactory" />
            <property name="connection" ref="connection" />
            <property name="session" ref="session" />
            <property name="messageListenerContainerFactory" ref="messageListenerContainerFactory"/>
            <property name="serviceDefinitionDao" ref="serviceDefinitionDao" />
            <property name="messageListeners">
                <list>
                    <!-- <ref bean="receiveItemSyncListener" /> -->
                    <ref bean="receiveItemDispositionConfirmListener" />
                   <!-- <ref bean="receiveBomSyncListener" />
                    <ref bean="receiveProcessRoutingSyncListener" />
                    <ref bean="receiveWOIssueListener" />
                    <ref bean="receiveWOOperationScheduleListener" />
                    <ref bean="receivePersonnelSyncListener" />
                    <ref bean="receiveLocationSyncListener" />
                    <ref bean="receiveWOStatusUpdateListener" />
                    <ref bean="receiveMaterialIssueListener" />
                    <ref bean="receivePOSyncListener" /> -->
                    <ref bean="receiveWOIssueConfirmListener" />
                    <ref bean="receiveWORevisionConfirmListener" />
                    <ref bean="receiveWORevisionDeltaConfirmListener" />
                    <ref bean="receiveWOSplitConfirmListener" />
                    <ref bean="receiveWORequestConfirmListener" />
                    <ref bean="receiveWOOperationStatusConfirmListener" />
                    <ref bean="receiveWOStatusConfirmListener" />
                    <ref bean="receivePesonnelClockingSyncConfirmListener" />
                    <ref bean="receiveProcessRoutingSyncConfirmListener" />
                   <!-- <ref bean="receivePOLineReceiptListener" />
                    <ref bean="receiveSupplierSyncListener" />
                    <ref bean="receiveExternalDatColListener" />
                    <ref bean="receiveOperTypeSyncListener" />
                    <ref bean="receiveMachineCycleListener" />
                    <ref bean="receiveEcnSyncListener" />
                    <ref bean="receiveNotifyCatalogSyncListener" />
                    <ref bean="receiveTestServiceListener" /> -->
                    <ref bean="receiveMBOMConfirmListener" />
                    <ref bean="receiveReplyItemSyncListener" />
                </list>
            </property>
            <property name="webServiceEndpoints">
                <list>
                  <!-- <ref bean="personnelSyncEndpoint"/>
                   <ref bean="locationSyncEndpoint"/>
                   <ref bean="operTypeSyncEndpoint"/>
                   <ref bean="woIssueEndpoint"/>
                   <ref bean="woOperationScheduleSyncEndpoint"/>
                   <ref bean="supplierSyncEndpoint"/>
                   <ref bean="receiveMaterialIssueEndpoint"/>
                   <ref bean="bomSyncEndpoint"/>
                   <ref bean="partMaterialSyncEndpoint"/>
                   <ref bean="purchaseOrderSyncEndpoint"/>
                   <ref bean="woStatusUpdateSyncEndpoint"/>
                   <ref bean="receivePOLineReceiptEndpoint"/>
                   <ref bean="receiveExternalDataCollectionEndpoint"/>
                   <ref bean="receiveProcessRoutingSyncEndpoint"/>
                   <ref bean="receiveToolSyncEndpoint"/> -->
                </list>
            </property>
        </bean>


    </beans>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ibaintegration-extensioncontext-cm
