apiVersion: v1
data:
  redis.properties: |
    redis.tokenrevocation.enabled=true
    redis.cluster.sentinel.nodes=redis://redis-sentinel-1.default.svc.cluster.local:26379,redis://redis-sentinel-2.default.svc.cluster.local:26379
    redis.cluster.sentinel.master=mymaster
    redis.cluster.pool.maxconnection=128

kind: ConfigMap
metadata:
  creationTimestamp: 2019-06-05T21:40:07Z
  name: iba-cm-redis
  namespace: default
  resourceVersion: "668103"
  selfLink: /api/v1/namespaces/default/configmaps/redisproperties
  uid: 7ca7c45b-87da-11e9-b6be-06e36b0b2240

