apiVersion: v1
data:
  samlContextConfig.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <beans xmlns:security="http://www.springframework.org/schema/security"
                 xmlns="http://www.springframework.org/schema/beans"
                 xmlns:context="http://www.springframework.org/schema/context"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xmlns:mvc="http://www.springframework.org/schema/mvc"
                 xsi:schemaLocation="http://www.springframework.org/schema/beans
                                         http://www.springframework.org/schema/beans/spring-beans-4.3.xsd
                                         http://www.springframework.org/schema/security
                                         http://www.springframework.org/schema/security/spring-security-4.2.xsd
                                         http://www.springframework.org/schema/context
                                         http://www.springframework.org/schema/context/spring-context-4.3.xsd
                                         http://www.springframework.org/schema/mvc http://www.springframework.org/schema/mvc/spring-mvc-4.3.xsd">
        <!-- UNCOMMENT TO ENABLE SSO IN IBA - START -->
        <!--
                             <context:property-placeholder location="classpath:/samlsso.properties" ignore-unresolvable="true" ignore-resource-not-found="true" />
            <context:component-scan base-package="com.ibaset.solumina.security.saml.core"/>
        <context:annotation-config/>
        <bean id="externalAuthenticationFilter"     class="com.ibaset.solumina.security.saml.servlet.SAMLSoluminaAuthenticationFilter" >
            <property name="loginService" ref="login"/>
            <property name="delegateProvider">
                            <bean
                                    class="org.springframework.security.authentication.dao.DaoAuthenticationProviderImpl">
                                    <property name="userDetailsService" ref="jdbcDaoImpl" />
                                    <property name="passwordEncoder">
                                            <ref bean="passwordEncoder" />
                                    </property>
                            </bean>
                    </property>
        </bean>
        <security:http security="none" pattern="/admin**"/>
        <security:http security="none" pattern="/favicon.ico"/>
        <security:http security="none" pattern="/images/**"/>
        <security:http security="none" pattern="/css/**"/>
        <security:http security="none" pattern="/logout.jsp"/>
        <security:http entry-point-ref="samlEntryPoint" use-expressions="false" pattern="/saml/**">
            <security:anonymous enabled="false" />
            <security:intercept-url pattern="/saml/**" access="IS_AUTHENTICATED_FULLY"/>
            <security:custom-filter before="FIRST" ref="metadataGeneratorFilter"/>
            <security:custom-filter after="BASIC_AUTH_FILTER" ref="samlFilter"/>
            <security:headers>
                    <security:frame-options policy="SAMEORIGIN" />
            </security:headers>
            <security:csrf disabled="true"/>
        </security:http>
        <security:http entry-point-ref="samlEntryPoint" use-expressions="false" pattern="/samllogindetails.jsp">
            <security:anonymous enabled="false" />
            <security:intercept-url pattern="/samllogindetails.jsp/**" access="IS_AUTHENTICATED_FULLY"/>
            <security:custom-filter before="FIRST" ref="metadataGeneratorFilter"/>
            <security:custom-filter after="BASIC_AUTH_FILTER" ref="samlFilter"/>
            <security:headers>
                    <security:frame-options policy="SAMEORIGIN" />
            </security:headers>
            <security:csrf disabled="true"/>
        </security:http>
        <security:http entry-point-ref="samlEntryPoint" use-expressions="false" pattern="/launcher.jsp">
            <security:anonymous enabled="false" />
            <security:intercept-url pattern="/launcher.jsp/**" access="IS_AUTHENTICATED_FULLY"/>
            <security:custom-filter before="FIRST" ref="metadataGeneratorFilter"/>
            <security:custom-filter after="BASIC_AUTH_FILTER" ref="samlFilter"/>
            <security:headers>
                    <security:frame-options policy="SAMEORIGIN" />
            </security:headers>
            <security:csrf disabled="true"/>
        </security:http>
        <security:http entry-point-ref="samlEntryPoint" use-expressions="false" pattern="/sso*">
            <security:anonymous enabled="false" />
            <security:intercept-url pattern="/ssologin.jsp/**" access="IS_AUTHENTICATED_FULLY"/>
            <security:intercept-url pattern="/ssologout.jsp/**" access="IS_AUTHENTICATED_FULLY"/>
            <security:custom-filter before="FIRST" ref="metadataGeneratorFilter"/>
            <security:custom-filter after="BASIC_AUTH_FILTER" ref="samlFilter"/>
            <security:headers>
                    <security:frame-options policy="SAMEORIGIN" />
            </security:headers>
            <security:csrf disabled="true"/>
        </security:http>
        <bean id="samlFilter" class="org.springframework.security.web.FilterChainProxy">
            <security:filter-chain-map request-matcher="ant">
                <security:filter-chain pattern="/saml/login/**" filters="samlEntryPoint"/>
                <security:filter-chain pattern="/saml/logout/**" filters="samlLogoutFilter"/>
                <security:filter-chain pattern="/saml/metadata/**" filters="metadataDisplayFilter"/>
                <security:filter-chain pattern="/saml/SSO/**" filters="samlWebSSOProcessingFilter"/>
                <security:filter-chain pattern="/saml/SSOHoK/**" filters="samlWebSSOHoKProcessingFilter"/>
                <security:filter-chain pattern="/saml/SingleLogout/**" filters="samlLogoutProcessingFilter"/>
                <security:filter-chain pattern="/saml/discovery/**" filters="samlIDPDiscovery"/>
            </security:filter-chain-map>
        </bean>
        <bean id="successRedirectHandler"
              class="com.ibaset.solumina.security.saml.core.SoluminaSAMLSuccessHandler">
                    <property name="defaultTargetUrl" value="/"/>
            <property name="loginService" ref="login"/>
        </bean>
        <bean id="failureRedirectHandler"
              class="org.springframework.security.web.authentication.SimpleUrlAuthenticationFailureHandler">
            <property name="useForward" value="true"/>
            <property name="defaultFailureUrl" value="/error.jsp"/>
        </bean>
        <security:authentication-manager id="samlAuthenticationManager">
            <security:authentication-provider ref="samlAuthenticationProvider"/>
            <security:authentication-provider ref="authProvider"/>
            <security:authentication-provider>
                <security:user-service id="adminInterfaceService">
                    <security:user name="admin" password="soluminaidpadmin" authorities="ROLE_ADMIN"/>
                </security:user-service>
            </security:authentication-provider>
        </security:authentication-manager>
        <bean id="samlLogger" class="org.springframework.security.saml.log.SAMLDefaultLogger"/>
        <bean id="keyManager" class="org.springframework.security.saml.key.JKSKeyManager">
            <constructor-arg value="classpath:security/samlKeystore.jks"/>
            <constructor-arg type="java.lang.String" value="nalle123"/>
            <constructor-arg>
                <map>
                   <entry key="solumina" value="nalle123"/>
                </map>
            </constructor-arg>
             <constructor-arg type="java.lang.String" value="solumina"/>
        </bean>
        <bean id="samlEntryPoint" class="org.springframework.security.saml.SAMLEntryPoint">
            <property name="defaultProfileOptions">
                <bean class="org.springframework.security.saml.websso.WebSSOProfileOptions">
                    <property name="includeScoping" value="false"/>
                </bean>
            </property>
        </bean>
        <bean id="metadataGeneratorFilter" class="org.springframework.security.saml.metadata.MetadataGeneratorFilter">
            <constructor-arg>
                <bean class="org.springframework.security.saml.metadata.MetadataGenerator">
                    <property name="extendedMetadata">
                        <bean class="org.springframework.security.saml.metadata.ExtendedMetadata">
                            <property name="idpDiscoveryEnabled" value="true"/>
                             <property name="requireLogoutRequestSigned" value="false"/>
                        </bean>
                    </property>
                </bean>
            </constructor-arg>
        </bean>
        <bean id="metadataDisplayFilter" class="org.springframework.security.saml.metadata.MetadataDisplayFilter"/>
        <bean id="contextProvider" class="org.springframework.security.saml.context.SAMLContextProviderImpl"/>
        <bean id="samlWebSSOProcessingFilter" class="org.springframework.security.saml.SAMLProcessingFilter">
            <property name="authenticationManager" ref="samlAuthenticationManager"/>
            <property name="authenticationSuccessHandler" ref="successRedirectHandler"/>
            <property name="authenticationFailureHandler" ref="failureRedirectHandler"/>
        </bean>
        <bean id="samlWebSSOHoKProcessingFilter" class="org.springframework.security.saml.SAMLWebSSOHoKProcessingFilter">
            <property name="authenticationManager" ref="samlAuthenticationManager"/>
            <property name="authenticationSuccessHandler" ref="successRedirectHandler"/>
            <property name="authenticationFailureHandler" ref="failureRedirectHandler"/>
        </bean>
        <bean id="logoutHandler"
              class="com.ibaset.solumina.security.saml.core.SoluminaContextLogoutHandler">
            <property name="invalidateHttpSession" value="true"/>
        </bean>
        <bean id="samlLogoutFilter" class="org.springframework.security.saml.SAMLLogoutFilter">
            <constructor-arg index="0" ref="successLogoutHandler"/>
            <constructor-arg index="1" ref="logoutHandler"/>
            <constructor-arg index="2" ref="logoutHandler"/>
        </bean>
        <bean id="samlLogoutProcessingFilter" class="org.springframework.security.saml.SAMLLogoutProcessingFilter">
            <constructor-arg index="0" ref="successLogoutHandler"/>
            <constructor-arg index="1" ref="logoutHandler"/>
        </bean>
        <bean id="processor" class="org.springframework.security.saml.processor.SAMLProcessorImpl">
            <constructor-arg>
                <list>
                    <ref bean="redirectBinding"/>
                    <ref bean="postBinding"/>
                    <ref bean="artifactBinding"/>
                    <ref bean="soapBinding"/>
                    <ref bean="paosBinding"/>
                </list>
            </constructor-arg>
        </bean>
        <bean id="webSSOprofileConsumer" class="org.springframework.security.saml.websso.WebSSOProfileConsumerImpl"/>
        <bean id="hokWebSSOprofileConsumer" class="org.springframework.security.saml.websso.WebSSOProfileConsumerHoKImpl"/>
        <bean id="webSSOprofile" class="org.springframework.security.saml.websso.WebSSOProfileImpl"/>
        <bean id="hokWebSSOProfile" class="org.springframework.security.saml.websso.WebSSOProfileConsumerHoKImpl"/>
        <bean id="ecpprofile" class="org.springframework.security.saml.websso.WebSSOProfileECPImpl"/>
        <bean id="logoutprofile" class="com.ibaset.solumina.security.saml.core.SoluminaSingleLogoutProfileImpl">
        </bean>
        <bean id="postBinding" class="org.springframework.security.saml.processor.HTTPPostBinding">
            <constructor-arg ref="parserPool"/>
            <constructor-arg ref="velocityEngine"/>
        </bean>
        <bean id="redirectBinding" class="org.springframework.security.saml.processor.HTTPRedirectDeflateBinding">
            <constructor-arg ref="parserPool"/>
        </bean>
        <bean id="artifactBinding" class="org.springframework.security.saml.processor.HTTPArtifactBinding">
            <constructor-arg ref="parserPool"/>
            <constructor-arg ref="velocityEngine"/>
            <constructor-arg>
                <bean class="org.springframework.security.saml.websso.ArtifactResolutionProfileImpl">
                    <constructor-arg>
                        <bean class="org.apache.commons.httpclient.HttpClient">
                            <constructor-arg>
                                <bean class="org.apache.commons.httpclient.MultiThreadedHttpConnectionManager"/>
                            </constructor-arg>
                        </bean>
                    </constructor-arg>
                    <property name="processor">
                        <bean class="org.springframework.security.saml.processor.SAMLProcessorImpl">
                            <constructor-arg ref="soapBinding"/>
                        </bean>
                    </property>
                </bean>
            </constructor-arg>
        </bean>
        <bean id="soapBinding" class="org.springframework.security.saml.processor.HTTPSOAP11Binding">
            <constructor-arg ref="parserPool"/>
        </bean>
        <bean id="paosBinding" class="org.springframework.security.saml.processor.HTTPPAOS11Binding">
            <constructor-arg ref="parserPool"/>
        </bean>
        <bean class="org.springframework.security.saml.SAMLBootstrap"/>
        <bean id="velocityEngine" class="org.springframework.security.saml.util.VelocityFactory" factory-method="getEngine"/>
        <bean id="parserPool" class="org.opensaml.xml.parse.StaticBasicParserPool" init-method="initialize"/>
        <bean id="parserPoolHolder" class="org.springframework.security.saml.parser.ParserPoolHolder"/>
            -->
        <!-- SSO - END -->
    </beans>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: iba-samlcontextconfig-cm
