apiVersion: v1
data:
  log4j.properties: "#\r\n# Proprietary and Confidential\r\n# Copyright 1995-2015
    iBASEt, Inc.\r\n# Unpublished-rights reserved under the Copyright Laws of the
    United States\r\n# US Government Procurements:\r\n# Commercial Software licensed
    with Restricted Rights.\r\n# Use, reproduction, or disclosure is subject to restrictions
    set forth in\r\n# license agreement and purchase contract.\r\n# iBASEt, Inc. 27442
    Portola Parkway, Suite 300, Foothill Ranch, CA 92610\r\n#\r\n# Solumina software
    may be subject to United States Dept of Commerce Export Controls.\r\n# Contact
    iBASEt for specific Expert Control Classification information.\r\n#\r\nlog4j.rootCategory=error,
    stdout, file\r\n\r\n# Set the log level for Inbound and Outbound services\r\nlog4j.logger.com.ibaset.solumina.execution.order.integration=info\r\nlog4j.logger.com.ibaset.solumina.execution.useractivity.integration=info\r\nlog4j.logger.com.ibaset.solumina.execution.po.integration=info\r\nlog4j.logger.com.ibaset.solumina.planning.bom.integration=info\r\nlog4j.logger.com.ibaset.solumina.planning.item.integration=info\r\nlog4j.logger.com.ibaset.solumina.planning.plan.integration=info\r\nlog4j.logger.com.ibaset.solumina.planning.ecn.integration=info\r\nlog4j.logger.com.ibaset.solumina.planning.notifycatalog.integration=info\r\nlog4j.logger.com.ibaset.solumina.systemadmin.location.integration=info\r\nlog4j.logger.com.ibaset.solumina.systemadmin.user.integration=info\r\nlog4j.logger.com.ibaset.solumina.systemadmin.opertype.integration=info\r\nlog4j.logger.com.ibaset.solumina.supplierquality.po.integration=info\r\nlog4j.logger.com.ibaset.solumina.supplierquality.supplier.integration=info\r\n\r\n#
    Console Appender Configuration\r\nlog4j.appender.stdout=org.apache.log4j.ConsoleAppender\r\nlog4j.appender.stdout.layout=org.apache.log4j.PatternLayout\r\nlog4j.appender.stdout.layout.ConversionPattern=%d
    %p [%c] - <%m>%n\r\n# Threshold is set to INFO for console appender\r\nlog4j.appender.stdout.Threshold=INFO\r\n\r\n#
    Solumina Rolling File Appender Configuration  \r\nlog4j.appender.file=com.ibaset.solumina.logging.appender.SoluminaRollingFileAppender\r\nlog4j.appender.file.layout=org.apache.log4j.PatternLayout\r\nlog4j.appender.file.layout.ConversionPattern=%d
    %p [%c] - <%m>%n\r\nlog4j.appender.file.DatePattern='.'yyyy-MM-dd\r\nlog4j.appender.file.MaximumFileSize=20MB\r\nlog4j.appender.file.MaxBackupIndex=5\r\nlog4j.appender.file.CompressBackups=true\r\nlog4j.appender.file.CompressionMaxDays=1\r\nlog4j.appender.file.DeleteBackups=true\r\nlog4j.appender.file.DeletionMaxDays=30\r\n\r\nlog4j.logger.com.ibaset.common.solumina.SoluminaCluster=info,
    file\r\nlog4j.additivity.com.ibaset.common.solumina.SoluminaCluster=false"
kind: ConfigMap
metadata:
  creationTimestamp: 2019-06-05T21:41:46Z
  name: iba-cm-log4j
  namespace: default
  resourceVersion: "668258"
  selfLink: /api/v1/namespaces/default/configmaps/log4j
  uid: b7ce9aff-87da-11e9-9ba1-0af663ddcdfa

