apiVersion: v1
data:
  solumina-G8.xml: "<Context useHttpOnly=\"true\" path=\"/solumina-G8\"\n    docBase=\"${catalina.home}/solumina/solumina-G8R2SP4.war\">\n\n
    \       <Resource\n                auth=\"Container\"\n                name=\"jdbc/soluminaPrivateDS\"\n
    \               type=\"javax.sql.DataSource\"\n                username=\"MT_CONPOOL_USER\"\n
    \               password=\"MT_CONPOOL_USER\"\n                driverClassName=\"com.microsoft.sqlserver.jdbc.SQLServerDriver\"\n
    \               defaultAutoCommit=\"false\"\n                maxIdle=\"25\"\n
    \               maxWaitMillis=\"2\"\n                minIdle=\"25\"\n                validationQuery=\"select
    getdate()\"\n                url=\"jdbc:sqlserver://--sqlip--;applicationName=SoluminaFND;instanceName=--instance_name--;databaseName=Solumina;schemaName=SFMFG;sendStringParametersAsUnicode=false\"\n
    \               maxTotal=\"50\"/>\n\n\n    <Resource name=\"jms/ConnectionFactory\"
    \n        auth=\"Container\"\n        type=\"org.apache.activemq.ActiveMQConnectionFactory\"\n
    \       factory=\"org.apache.activemq.jndi.JNDIReferenceFactory\"\n        brokerURL=\"vm://localhost\"
    />\n    \n    <Resources allowLinking=\"true\" className=\"org.apache.catalina.webresources.StandardRoot\">\n
    \       <PreResources\n            className=\"org.apache.catalina.webresources.DirResourceSet\"\n
    \           base=\"/opt/config/driver\"\n            webAppMount=\"/WEB-INF/lib\"
    />\n        <PreResources\n            className=\"org.apache.catalina.webresources.DirResourceSet\"\n
    \           base=\"/opt/config/props\"\n            webAppMount=\"/WEB-INF/classes\"
    />\n    </Resources>\n\n</Context>\n"
kind: ConfigMap
metadata:
  creationTimestamp: 2019-08-20T21:23:58Z
  name: iba-cm-soluminag8-sql
  namespace: default
  resourceVersion: "180022"
  selfLink: /api/v1/namespaces/default/configmaps/iba-cm-soluminag8-sql
  uid: d246252c-c390-11e9-9868-0a19a1cbbb20

