// If no preperation is required, remove all content from here

==== Prepare your AWS account

Amazon Elasticsearch Service uses AWS Identity and Access Management (IAM) service-linked roles. A service-linked role is a unique type of IAM role that is linked directly to Amazon ES. Service-linked roles are predefined by Amazon ES and include all the permissions that the service requires to call other AWS services on your behalf. This role can be created by running cloudformation template located under templates/elk-service-linked-role.yaml. or please refer https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/slr-es.html[Service-linked role for Amazon ES^].

Amazon Elastic Kubernetes Service uses Elastic Container Registry to pull images. Hence, authorization needs to be provided for your AWS account so that images can be pulled at deployment. Contact https://www.ibaset.com/contact/[iBASEt^] sales and provide your AWS Account ID which is a 12 digit number, such as 123456789012, that uniquely identifies an AWS account. Information on how to find AWS Account ID is https://docs.aws.amazon.com/general/latest/gr/acct-identifiers.html[here^]. Once AWS Account ID is added to Elastic Container Registry on iBASEt account, Quick start can be deployed successfully. You can also request a trial license mentioned in "Test the deployment" section later at the same time.

// ==== Prepare your {partner-company-name} account

// _Describe any setup required in the partner portal/account prior to template launch_

// ==== Prepare for the deployment

// _Describe any preparation required to complete the product build, such as obtaining licenses or placing files in S3_
