// If no preperation is required, remove all content from here

==== Prepare your AWS account

Amazon Elasticsearch Service uses AWS Identity and Access Management (IAM) service-linked roles. A service-linked role is a unique type of IAM role that links directly to Amazon ES. Service-linked roles are predefined by Amazon ES and include all of the required permissions to call other AWS services on your behalf. This role can be created by running the AWS CloudFormation template located under `templates/elk-service-linked-role.yaml`. For more information, see https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/slr-es.html[Using Service-Linked Roles for Amazon ES^].

Amazon EKS uses Amazon Elastic Container Registry (Amazon ECR) to fetch images. In order to fetch images for this deployement, you must authorize this activity in your AWS account. Contact https://www.ibaset.com/contact/[iBASEt^] sales and provide your AWS account ID, which is a 12-digit number that uniquely identifies your AWS account. For more information, see https://docs.aws.amazon.com/general/latest/gr/acct-identifiers.html[Your AWS account identifiers^]. This Quick Start can be deployed successfully once your AWS account ID is added to Amazon ECR in your iBASEt account. You can also request a trial license, as discussed in the link:#_deployment_options[Test the deployment] section of this guide.

// ==== Prepare your {partner-company-name} account

// _Describe any setup required in the partner portal/account prior to template launch_

// ==== Prepare for the deployment

// _Describe any preparation required to complete the product build, such as obtaining licenses or placing files in S3_
