apiVersion: v1
data:
  solumina-G8.xml: "<Context useHttpOnly=\"true\" path=\"/solumina-G8\"\n    docBase=\"${catalina.home}/solumina/solumina-G8R2SP4.war\">\n\n
    \        <Resource\n                auth=\"Container\"\n                name=\"jdbc/soluminaPrivateDS\"\n
    \               type=\"javax.sql.DataSource\"\n                username=\"MT_CONPOOL_USER\"\n
    \               password=\"mt_conpool_user\"\n                driverClassName=\"oracle.jdbc.driver.OracleDriver\"\n
    \               defaultAutoCommit=\"false\"\n                accessToUnderlyingConnectionAllowed=\"true\"\n
    \               maxIdle=\"25\"\n                maxWaitMillis=\"2\"\n                minIdle=\"25\"\n
    \               validationQuery=\"select sysdate from dual\"\n                url=\"jdbc:oracle:thin:@dexui.c4jsc5ks7f1j.us-west-1.rds.amazonaws.com:1521:DEXUI\"\n
    \               maxTotal=\"50\"/>\n\n\n\n    <Resource name=\"jms/ConnectionFactory\"
    \n        auth=\"Container\"\n        type=\"org.apache.activemq.ActiveMQConnectionFactory\"\n
    \       factory=\"org.apache.activemq.jndi.JNDIReferenceFactory\"\n        brokerURL=\"vm://localhost\"
    />\n    \n    <Resources allowLinking=\"true\" className=\"org.apache.catalina.webresources.StandardRoot\">\n
    \       <PreResources\n            className=\"org.apache.catalina.webresources.DirResourceSet\"\n
    \           base=\"/opt/config/driver\"\n            webAppMount=\"/WEB-INF/lib\"
    />\n        <PreResources\n            className=\"org.apache.catalina.webresources.DirResourceSet\"\n
    \           base=\"/opt/config/props\"\n            webAppMount=\"/WEB-INF/classes\"
    />\n    </Resources>\n\n</Context>\n\n"
kind: ConfigMap
metadata:
  creationTimestamp: 2019-07-05T20:58:07Z
  name: iba-cm-soluminag8-oracle
  namespace: default
  resourceVersion: "1864362"
  selfLink: /api/v1/namespaces/default/configmaps/iba-cm-soluminag8-oracle
  uid: 96f74a7d-9f67-11e9-a20e-06d559b57a96

