apiVersion: v1
kind: Service
metadata:
  name: iba
spec:
  selector:
    app: iba
  ports:
  - name: iba2
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: iba1
    protocol: TCP
    port: 8009
    targetPort: 8009
#  type: LoadBalancer
