apiVersion: v1
kind: Service
metadata:
  name: configurator
spec:
  selector:
    app: configurator
  ports:
  - name: http
    protocol: TCP
    port: 5021
    targetPort: 5021
#  type: LoadBalancer
