apiVersion: v1
data:
  application.yml: |
    server:
      servlet:
        context-path: /solumina-user-info/api
      port: 8091
    spring:
      profiles:
        include:
         - tomcat # must have profile
         - redis # must have profile
         - ACTIVATED_PROFILE_FOR_DATABASE # Possible values - oracle, sqlserver
         - mongodb # must have profile
      devtools:
        restart:
          exclude: logs/**
      servlet:
        multipart:
          max-file-size: 100MB
          max-request-size: 100MB
      main:
         allow-bean-definition-overriding: true
      cloud:
        refresh:
          enabled: false
      autoconfigure:
        exclude:
           - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
           - org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration
           - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    security:
      oauth2:
        resource:
          jwt:
            key-value: solumina+$ibaset
    zipkin:
      server:
        url: http://zipkin:9411

    solumina:
      serviceName: solumina-user-info

    swagger:
      title: Solumina REST API
      description: "REST API for integrating with Solumina Middle Tier. All API endpoint will return a response object which will contain 3 parameters 'data': it will have actual response data (API Endpoint specific response model shown in API documentation will be available in 'data' parameter of original repsonse object), 'meta': it will have some metadata information, 'error': error information if api response have any error."
      version: 1.0
      termsOfServiceUrl: https://www.ibaset.com
      license: Ibaset Proprietary API
      licenseUrl: https://www.ibaset.com
      contactName: iBASEt
      contactUrl: https://www.ibaset.com
      contactEmail: support@ibaset.com
    defaultSchema: SFMFG
    management:
      endpoints:
        web:
          exposure:
            include: metrics
      metrics:
        enable:
          http.server.requests: true
          all: false
        export:
          elastic:
            host: https://--es--:443
            step: 60m
kind: ConfigMap
metadata:
  name: userinfo-application-cm
