apiVersion: v1
data:
  application-mongodb.yml: |
    #Local MongoDB config
    #spring:
    #  data:
    #    mongodb:
    #      authentication-database: admin
    #      username: root
    #      password: root
    #      database : solumina_user
    #      port: 27017
    #      host: localhost

    #Mongodb server config with replicaset
    spring:
      data:
        mongodb:
          uri: mongodb://admin:--MongoDBAdminPassword--@--mongoprimaryip--:27017,--mongosecondaryip0--:27017,--mongosecondaryip1--:27017/admin?replicaSet=s0
kind: ConfigMap
metadata:
  creationTimestamp: 2019-06-11T17:12:05Z
  name: userinfo-cm-mongodb
  namespace: default
  resourceVersion: "1431062"
  selfLink: /api/v1/namespaces/default/configmaps/userinfo-cm-mongodb
  uid: 0999f011-8c6c-11e9-9ba1-0af663ddcdfa
