apiVersion: v1
data:
  redis.properties: |
    ################################################################
    # Redis properties
    # Eventually this should be moved to Spring Cloud Config Server
    ################################################################
    redis.tokenrevocation.enabled=true

    #For External redis config
    #redis.cluster.sentinel.nodes=REDIS_IP1:PORT1,REDIS_IP2:PORT2,REDIS_IP3:PORT3
    #redis.cluster.sentinel.master=redis-cluster

    redis.cluster.sentinel.nodes=redis://redis-sentinel-1.default.svc.cluster.local:26379,redis://redis-sentinel-2.default.svc.cluster.local:26379
    redis.cluster.sentinel.master=mymaster
    redis.cluster.pool.maxconnection=128

    #Because of Spring bug: https://jira.spring.io/browse/SPR-9989, cannot specify default with @Value, so passing empty from property file
    #redis.cluster.sentinel.nodes=
    #redis.cluster.sentinel.master=
    #redis.cluster.pool.maxconnection=128
kind: ConfigMap
metadata:
  creationTimestamp: 2019-06-11T17:13:16Z
  name: userinfo-cm-redis
  namespace: default
  resourceVersion: "1431172"
  selfLink: /api/v1/namespaces/default/configmaps/userinfo-cm-redis
  uid: 33de00e2-8c6c-11e9-b6be-06e36b0b2240

