apiVersion: v1
data:
  application-mongodb.yml: |
    #Local MongoDB config
    #spring:
    #  data:
    #    mongodb:
    #      authentication-database: admin
    #      username: root
    #      password: root
    #      database : solumina_user
    #      port: 27017
    #      host: localhost

    #Mongodb server config with replicaset
    spring:
      data:
        mongodb:
          uri: mongodb://solumina_user:solumina_user@--mongoprimaryip--:27017,--mongosecondaryip0--:27017,--mongosecondaryip1--:27017/solumina_user?replicaSet=s0
kind: ConfigMap
metadata:
  name: userinfo-applicationmongodb-cm
