[file]
[backends]
  [backends.ui]
     [backends.ui.servers.server1]
       url="https://--DNS_NAME--"

[frontends]
  [frontends.iba]
    backend = "ui"
          passHostHeader = true
    [frontends.iba.routes.iba_1]
          rule = "PathPrefix:/solumina-mt/;ReplacePathRegex:/solumina-mt/ /solumina-G8/"

  [frontends.iba1]
    backend = "ui"
          passHostHeader = true
    [frontends.iba1.routes.iba_2]
          rule = "PathPrefix:/s2sapi/;ReplacePathRegex:/s2sapi/ /solumina-G8/api/s2s/v1.0/"

  [frontends.iba2]
    backend = "ui"
          passHostHeader = true
    [frontends.iba2.routes.iba_3]
          rule = "PathPrefix:/api/;ReplacePathRegex:/api/ /solumina-G8/api/v1.0/"

  [frontends.iba3]
    backend = "ui"
          passHostHeader = true
    [frontends.iba3.routes.iba_4]
          rule = "PathPrefix:/solumina-G8/health;ReplacePathRegex:/solumina-G8/health /solumina-G8/api/health"

  [frontends.iba4]
    backend = "ui"
          passHostHeader = true
    [frontends.iba4.routes.iba_5]
          rule = "PathPrefix:/solumina-G8/api/"

  [frontends.userinfo]
    backend = "ui"
          passHostHeader = false
    [frontends.userinfo.routes.userinfo1]
          rule = "PathPrefix:/api/user-avatar/;ReplacePathRegex:/api/user-avatar/ /solumina-user-info/api/v1.0/"

  [frontends.userinfo2]
    backend = "ui"
          passHostHeader = false
    [frontends.userinfo2.routes.userinfo2]
          rule = "PathPrefix:/solumina-user-info/health;ReplacePathRegex:/solumina-user-info/health /solumina-user-info/api/health"

  [frontends.userinfo3]
    backend = "ui"
          passHostHeader = false
    [frontends.userinfo3.routes.userinfo3]
          rule = "PathPrefix:/solumina-user-info/api/"

  [frontends.notification]
    backend = "ui"
          passHostHeader = true
    [frontends.notification.routes.notification1]
          rule = "PathPrefix:/api/notification/;ReplacePathRegex:/api/notification/ /"

  [frontends.search]
    backend = "ui"
          passHostHeader = false
    [frontends.search.routes.search1]
          rule = "PathPrefix:/api/search;ReplacePathRegex:/api/search /solumina-search/api/v1.0/globalsearch"

  [frontends.search2]
    backend = "ui"
          passHostHeader = false
    [frontends.search2.routes.search2]
          rule = "PathPrefix:/solumina-search/health;ReplacePathRegex:/solumina-search/health /solumina-search/api/health"

  [frontends.search3]
    backend = "ui"
          passHostHeader = false
    [frontends.search3.routes.search3]
          rule = "PathPrefix:/solumina-search/api/"
  
  [frontends.login]
    backend = "ui"
          passHostHeader = false
    [frontends.login.routes.login]
          rule = "PathPrefix:/,/api/login/"

  [frontends.supervisor]
    backend = "ui"
          passHostHeader = false
    [frontends.supervisor.routes.supervisor]
          rule = "PathPrefix:/supervisor"

##  [frontends.zipkin]
##    backend = "ui"
##          passHostHeader = true
##    [frontends.zipkin.routes.zipkin1]
###          rule = "PathPrefix:/diagnostics/api/v1/spans, /zipkin;ReplacePathRegex:/diagnostics/api/v1/spans /api/v2/spans"
##           rule = "PathPrefix:/diagnostics/api/v1/spans, /zipkin"