apiVersion: v1
data:
  application-oracle.yml: |-
    # Oracle DB configuration
    app:
      db-name: oracle

    datasource:
      driverClass: oracle.jdbc.driver.OracleDriver
      jdbcUrl: CONN_STRING
      username: MT_CONPOOL_USER
      password: MT_CONPOOL_USER
      maximumPoolSize: 200
      minimumIdle: 25
      connectionTestQuery: select 1 from dual
      autoCommit: false
      connectionTimeout: 120000
      idleTimeout: 30000
      leakDetectionThreshold: 180000
      validationTimeout: 10000
      maxLifetime: 1800000
      implicitCachingEnabled: true
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: search-app-oracle-cm
