AWSTemplateFormatVersion: "2010-09-09"
Resources:
  BastionIbasetPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'ssm:DescribeParameters'
              - 'ssm:GetParameter'
              - 'ssm:GetParameters'
              - 'ssm:DeleteParameter'
              - 'ssm:DeleteParameters'
              - 'ssm:PutParameters'
              - 'ssm:PutParameter'
              - 's3:*'
              - 'elasticloadbalancing:Describe*'
            Resource: '*'
Outputs:
  BastionPolicyARN:
    Value:  !Ref BastionIbasetPolicy
