AWSTemplateFormatVersion: "2010-09-09"
Description: Creates KMS Key ID
Resources:
  KMSKeyID:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: '*'
            Action: 'kms:*'
            Resource: '*'
Outputs:
  KMSKeyID:
    Value: !Ref 'KMSKeyID'
    Description: KMS Key ID