AWSTemplateFormatVersion: 2010-09-09
Description: Creates a A-record set in hosted zone in Route53
Parameters:
  R53HostedZoneName:
    Type: String
  R53LBRecordSetName:
    Type: String
    Default: dhruvit.solibaset.com
  LBENDPOINT:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: LBENDPOINT
  LBHOSTEDZONE:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: LBHOSTEDZONE
Resources:
  SoluminaALBRecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      AliasTarget:
        DNSName: !Ref 'LBENDPOINT'
        HostedZoneId: !Ref 'LBHOSTEDZONE'
      HostedZoneName: !Ref 'R53HostedZoneName'
      Comment: A recordset for traefik loadbalancer
      Name: !Ref 'R53LBRecordSetName'
      Type: A