apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash-component-part
spec:
  template:
    metadata:
      labels:
        app: logstash-componenct-part
    spec:
      containers:
      - image: docker.elastic.co/logstash/logstash:6.7.0
        name: logstash-componenct-part
        ports:
        - name: logstash
          containerPort: 5044
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          readOnly: true
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
          readOnly: true
        - name: driver
          mountPath: /opt/logstash/driver
        - name: logs
          mountPath: /opt/logstash/lastrun
        - name: data
          mountPath: /usr/share/logstash/data
        args:
        - -f
        - /usr/share/logstash/pipeline/logstash.conf
        resources:
          limits:
            memory: 2Gi
            cpu: "500m"
          requests:
            memory: 2Gi
            cpu: "200m"
      volumes:

      - name: logs
        nfs:
         server: --fs--.efs.--region--.amazonaws.com 
         path: /logstash/logs/componenct-part

      - name: data
        nfs:
          server: --fs--.efs.--region--.amazonaws.com
          path: /logstash/data/componenct-part


      - name: driver
        nfs:
          server: --fs--.efs.--region--.amazonaws.com 
          path: /driver

      - name: pipeline
        configMap:
          name: logstash-componentpart-cm-sql
          items:
          - key: logstash.conf
            path: logstash.conf

      - name: config
        configMap:
          name: logstash-componentpart-cm-sql
          items:
          - key: logstash.yml
            path: logstash.yml
