apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: supervisor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: supervisor
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
#  - type: Resource
#    resource:
#      name: memory
#      targetAverageValue: 80Mi
