apiVersion: apps/v1
kind: Deployment
metadata:
  name: supervisor
  labels:
    app: supervisor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supervisor
  template:
    metadata:
      labels:
        app: supervisor
    spec:
      containers:
      - name: supervisor
        image: "279559645400.dkr.ecr.us-west-1.amazonaws.com/solui/supervisor:G8R2SP4"
        ports:
        - containerPort: 5020
        resources:
           requests:
            cpu: 200m
            memory: 64Mi

        volumeMounts:
        - name: supervisor-mount
          mountPath: /opt/ibaset/solumina-web-supervisor/config/


      volumes:
       - name: supervisor-mount
         configMap:
            defaultMode: 420
            items:
            - key: supervisorconfig
              path: .env
            name: supervisor-cm
