apiVersion: v1
kind: ConfigMap
metadata:
  name: zipkin-cm
data:
  STORAGE_TYPE: "elasticsearch"
  ES_HOSTS: "elasticsearch-coordinator"
  ES_INDEX_SHARDS: "2"
  ES_INDEX_REPLICAS: "2"
  SELF_TRACING_ENABLED: "true"
  JAVA_OPTS: "-Dlogging.level.zipkin=DEBUG"