apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-1
spec:
  selector:
    app: redis-sentinel-1
  ports:
  - name: redis-sentinel-1
    protocol: TCP
    port: 26379
    targetPort: 26379
#  type: LoadBalancer
